const KNOWN_NEWS_ENTITIES = [
  // Characters & Heroes
  "Spider-Man",
  "Batman",
  "Superman",
  "Wonder Woman",
  "Green Lantern",
  "Flash",
  "Wolverine",
  "Deadpool",
  "Iron Man",
  "Captain America",
  "Thor",
  "Hulk",
  "Black Panther",
  "Doctor Strange",
  "Venom",
  "Carnage",
  "Knull",
  "Daredevil",
  "Punisher",
  "Ghost Rider",
  "Silver Surfer",
  "Thanos",
  "Doctor Doom",
  "Magneto",
  "Joker",
  "Harley Quinn",
  "Catwoman",
  "Robin",
  "Nightwing",
  "Shazam",
  "Aquaman",
  "Spawn",
  "Hellboy",
  "Invincible",
  "Miracleman",
  "Sandman",
  "Lucifer",
  "Swamp Thing",
  "Constantine",
  "Watchmen",
  "Teen Titans",
  "Justice League",
  "The Avengers",
  "X-Men",
  "Fantastic Four",
  "Sinister Six",
  "Thunderbolts",
  "Suicide Squad",

  // Major Publishers & Imprints
  "Marvel",
  "DC Comics",
  "Image Comics",
  "Dark Horse",
  "IDW Publishing",
  "BOOM! Studios",
  "Dynamite Entertainment",
  "Valiant Comics",
  "2000 AD",
  "Vertigo",
  "Black Label",
  "Ultimate Marvel",
  "Krakoa",
  "Absolute Universe",
  "Shueisha",
  "Kodansha",
  "Shogakukan",
  "Viz Media",
  "Kadokawa",
  "Crunchyroll",

  // Manga & Anime Terms & Franchises
  "Manga",
  "Mangaka",
  "Anime",
  "Shonen",
  "Shojo",
  "Seinen",
  "Webtoon",
  "Manhwa",
  "One Piece",
  "Dragon Ball",
  "Naruto",
  "Bleach",
  "My Hero Academia",
  "Jujutsu Kaisen",
  "Demon Slayer",
  "Chainsaw Man",
  "Attack on Titan",
  "Berserk",
  "Akira",
  "JoJo's Bizarre Adventure",

  // Grading, Census & Market Authorities
  "CGC",
  "CBCS",
  "PSA",
  "ComicBase",
  "GoCollect",
  "Overstreet",
  "Heritage Auctions",
  "Goldin",
  "Metropolis Comics",
  "ComicConnect",

  // Media Conglomerates & Studios
  "Disney",
  "Marvel Studios",
  "Warner Bros",
  "DC Studios",
  "Warner Bros Discovery",
  "Paramount",
  "Skydance",
  "Sony Pictures",
  "Universal Pictures",
  "Peacock",
  "Max",
  "Netflix",
] as const;

export function findNewsEntities(headline: string, summary: string | null) {
  const text = `${headline} ${summary || ""}`;
  return KNOWN_NEWS_ENTITIES.filter((entity) => new RegExp(`\\b${entity.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\b`, "i").test(text));
}
