import fs from "fs";
import path from "path";
import { RawAuctionListing } from "../lib/sniper/types";

const GCS_BASE = "https://storage.googleapis.com/panel-profits-covers-all/Pictures";

const MULTI_SOURCE_AUCTIONS: RawAuctionListing[] = [
  // ==========================================
  // 1. ATOMIC AVENUE (ComicBase Direct Network)
  // ==========================================
  {
    id: "atomic-4829101",
    source: "atomicavenue",
    title: "Batman #423 CGC 9.8 Cracked Case Reholder Candidate McFarlane Cover",
    currentBid: 520.00,
    shippingCost: 15.00,
    bidCount: 8,
    secondsRemaining: 48, // < 1m Instant Snipe!
    url: "https://atomicavenue.com/atomic/issue/4829101/Batman-423",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/423.jpg`,
    certNumber: "3849201004",
    fairMarketValue: 1250.00,
    anchorFmv: 1250.00,
    pricingSourceProvenance: "GPA Analysis 90-Day Comp Index & Atomic Avenue Realized Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 3450,
    censusCount98: 412,
    censusHigher: 0,
    censusScarcityTier: "Iconic Copper Key (Todd McFarlane Classic)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Atomic Avenue Verified Slab Desk: CGC 9.8 top left corner cracked shell from transit. Inner archival well completely uncompromised. Perfect $25 reholder candidate against $1,250 FMV."
  },
  {
    id: "atomic-4829102",
    source: "atomicavenue",
    title: "Swamp Thing #37 CGC 9.8 1st John Constantine Alan Moore Landmark",
    currentBid: 980.00,
    shippingCost: 18.00,
    bidCount: 16,
    secondsRemaining: 105, // < 2m Red Hot!
    url: "https://atomicavenue.com/atomic/issue/4829102/Swamp-Thing-37",
    imageUrl: `${GCS_BASE}/D/DC/S/Swamp Thing (2nd Series)/37.jpg`,
    certNumber: "4019283002",
    fairMarketValue: 2400.00,
    anchorFmv: 2400.00,
    pricingSourceProvenance: "GPA Analysis 90-Day Comp Index & Heritage Realized Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 1820,
    censusCount98: 245,
    censusHigher: 0,
    censusScarcityTier: "Blue Chip Copper Key (1st Constantine)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Atomic Avenue Verified Exchange: CGC 9.8 White Pages. Prime 1st John Constantine. Live bidding concluding now."
  },
  {
    id: "atomic-4829103",
    source: "atomicavenue",
    title: "Batman: Ego #1 CGC 9.8 Darwyn Cooke Masterpiece Premiere",
    currentBid: 95.00,
    shippingCost: 12.00,
    bidCount: 4,
    secondsRemaining: 240, // < 5m Closing!
    url: "https://atomicavenue.com/atomic/issue/4829103/Batman-Ego-1",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman - Ego/1.jpg`,
    certNumber: "3920194005",
    fairMarketValue: 280.00,
    anchorFmv: 280.00,
    pricingSourceProvenance: "GPA Realized Index & ComicLink Realized Comps",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 420,
    censusCount98: 88,
    censusHigher: 0,
    censusScarcityTier: "Prestige Key (The Batman Film Inspiration)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Atomic Avenue Dealer Stock: CGC 9.8 White Pages. Darwyn Cooke masterpiece."
  },
  {
    id: "atomic-4829104",
    source: "atomicavenue",
    title: "Batman #0 CGC 9.8 New 52 Sunk Cost Grading Loss Sale",
    currentBid: 32.00,
    shippingCost: 10.00,
    bidCount: 2,
    secondsRemaining: 420, // < 10m Microwave!
    url: "https://atomicavenue.com/atomic/issue/4829104/Batman-0",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/0.jpg`,
    certNumber: "4192019001",
    fairMarketValue: 85.00,
    anchorFmv: 85.00,
    pricingSourceProvenance: "GPA Analysis 90-Day Comp Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 840,
    censusCount98: 310,
    censusHigher: 0,
    censusScarcityTier: "Modern Slab Value Floor",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Atomic Avenue Floor Liquidation: CGC 9.8 White Pages. Total cost below $45 grading fee."
  },
  {
    id: "atomic-4829105",
    source: "atomicavenue",
    title: "Batamn #423 CGC 9.8 Todd McFarlane Typo Sleeper",
    currentBid: 410.00,
    shippingCost: 15.00,
    bidCount: 3,
    secondsRemaining: 720, // < 15m On Deck!
    url: "https://atomicavenue.com/atomic/issue/4829105/Batamn-423",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/423.jpg`,
    certNumber: "3849102008",
    fairMarketValue: 1250.00,
    anchorFmv: 1250.00,
    pricingSourceProvenance: "GPA Realized Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 3450,
    censusCount98: 412,
    censusHigher: 0,
    censusScarcityTier: "Stealth Typo Listing (Zero Visibility)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Atomic Avenue Community Seller: Title misspelled as 'Batamn #423'. Undiscovered by search crawlers."
  },

  // ==========================================
  // 2. HERITAGE AUCTIONS (HA.com Weekly & Signature)
  // ==========================================
  {
    id: "heritage-829101",
    source: "heritage",
    title: "Green Lantern #76 CBCS 9.6 Cracked Corner Shell Reholder Play Neal Adams",
    currentBid: 480.00,
    shippingCost: 22.00,
    bidCount: 11,
    secondsRemaining: 55, // < 1m Instant Snipe!
    url: "https://comics.ha.com/itm/bronze-age/green-lantern-76-cbcs-96/829101.s",
    imageUrl: `${GCS_BASE}/D/DC/G/Green Lantern (2nd Series)/76.jpg`,
    certNumber: "21-049281-002",
    fairMarketValue: 1450.00,
    anchorFmv: 1450.00,
    pricingSourceProvenance: "Heritage Auctions Realized Signature Sales",
    gradingCompany: "CBCS",
    resolvedGrade: 9.6,
    censusTotal: 980,
    censusCount98: 42,
    censusHigher: 1,
    censusScarcityTier: "Bronze Age Landmark (Hard-Traveling Heroes)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Heritage Sunday Comic Auction: CBCS 9.6 with hairline crack on bottom bumper. Archival comic slab undisturbed. Immediate crossover or reholder candidate."
  },
  {
    id: "heritage-829102",
    source: "heritage",
    title: "Batman #181 CGC 9.4 1st Poison Ivy Carmine Infantino Cover",
    currentBid: 1650.00,
    shippingCost: 25.00,
    bidCount: 22,
    secondsRemaining: 88, // < 2m Red Hot!
    url: "https://comics.ha.com/itm/silver-age/batman-181-cgc-94/829102.s",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/181.jpg`,
    certNumber: "3720194001",
    fairMarketValue: 3400.00,
    anchorFmv: 3400.00,
    pricingSourceProvenance: "Heritage Auctions Realized Auction Archive",
    gradingCompany: "CGC",
    resolvedGrade: 9.4,
    censusTotal: 1420,
    censusCount98: 8,
    censusHigher: 0,
    censusScarcityTier: "Silver Age Holy Grail Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Heritage Weekly Comics Session: CGC 9.4 Off-White to White Pages. Complete with centerfold pin-up intact."
  },
  {
    id: "heritage-829103",
    source: "heritage",
    title: "House of Secrets #92 CGC 9.4 1st Swamp Thing Bernie Wrightson Cover",
    currentBid: 2100.00,
    shippingCost: 25.00,
    bidCount: 29,
    secondsRemaining: 180, // < 5m Closing!
    url: "https://comics.ha.com/itm/bronze-age/house-of-secrets-92-cgc-94/829103.s",
    imageUrl: `${GCS_BASE}/D/DC/H/House of Secrets/92.jpg`,
    certNumber: "3649201009",
    fairMarketValue: 4500.00,
    anchorFmv: 4500.00,
    pricingSourceProvenance: "Heritage Auctions 90-Day Comp Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.4,
    censusTotal: 1640,
    censusCount98: 14,
    censusHigher: 0,
    censusScarcityTier: "Bronze Age Mega Key #1",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Heritage Weekly Session: CGC 9.4 White Pages. Bernie Wrightson classic cover art."
  },
  {
    id: "heritage-829104",
    source: "heritage",
    title: "All-Star Comics #58 CGC 9.8 1st Power Girl Bronze Age Key",
    currentBid: 420.00,
    shippingCost: 20.00,
    bidCount: 12,
    secondsRemaining: 540, // < 10m Microwave!
    url: "https://comics.ha.com/itm/bronze-age/all-star-comics-58-cgc-98/829104.s",
    imageUrl: `${GCS_BASE}/D/DC/A/All-Star Comics/58.jpg`,
    certNumber: "3892019003",
    fairMarketValue: 980.00,
    anchorFmv: 980.00,
    pricingSourceProvenance: "Heritage Auctions Realized Signature Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 740,
    censusCount98: 84,
    censusHigher: 0,
    censusScarcityTier: "High Grade Bronze Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Heritage Comics Lot: CGC 9.8 White Pages. 1st Appearance Power Girl (Kara Zor-L)."
  },

  // ==========================================
  // 3. MYCOMICSHOP (Lone Star Auctions)
  // ==========================================
  {
    id: "mcs-7819201",
    source: "mycomicshop",
    title: "DC Comics Presents #26 CGC 9.8 1st New Teen Titans Cyborg Starfire Raven",
    currentBid: 560.00,
    shippingCost: 14.00,
    bidCount: 19,
    secondsRemaining: 42, // < 1m Instant Snipe!
    url: "https://www.mycomicshop.com/auctions/item?id=7819201",
    imageUrl: `${GCS_BASE}/D/DC/D/DC Comics Presents/26.jpg`,
    certNumber: "3948201004",
    fairMarketValue: 1250.00,
    anchorFmv: 1250.00,
    pricingSourceProvenance: "GPA Analysis & MyComicShop Realized Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 2950,
    censusCount98: 310,
    censusHigher: 0,
    censusScarcityTier: "Copper/Bronze Key (George Pérez Art)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "MyComicShop Weekly Prime Auction: CGC 9.8 White Pages. 1st New Teen Titans preview insert."
  },
  {
    id: "mcs-7819202",
    source: "mycomicshop",
    title: "Batman #357 CGC 9.8 1st Jason Todd Killer Croc Cracked Slab Reholder Arb",
    currentBid: 190.00,
    shippingCost: 14.00,
    bidCount: 7,
    secondsRemaining: 110, // < 2m Red Hot!
    url: "https://www.mycomicshop.com/auctions/item?id=7819202",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/357.jpg`,
    certNumber: "3829104006",
    fairMarketValue: 450.00,
    anchorFmv: 450.00,
    pricingSourceProvenance: "GPA Realized Comp Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 1100,
    censusCount98: 142,
    censusHigher: 0,
    censusScarcityTier: "Bronze Age Key Grail",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "MyComicShop Consignment: CGC 9.8 case cracked on lower rear rail. Book flawless. High-spread $25 reholder arbitrage play."
  },
  {
    id: "mcs-7819203",
    source: "mycomicshop",
    title: "Batman #232 CGC 9.6 1st Ra's al Ghul Neal Adams Classic Cover",
    currentBid: 680.00,
    shippingCost: 16.00,
    bidCount: 15,
    secondsRemaining: 280, // < 5m Closing!
    url: "https://www.mycomicshop.com/auctions/item?id=7819203",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/232.jpg`,
    certNumber: "3749201007",
    fairMarketValue: 1400.00,
    anchorFmv: 1400.00,
    pricingSourceProvenance: "MyComicShop Auction History",
    gradingCompany: "CGC",
    resolvedGrade: 9.6,
    censusTotal: 1250,
    censusCount98: 38,
    censusHigher: 0,
    censusScarcityTier: "Bronze Age Landmark",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "MyComicShop Auction: CGC 9.6 White Pages. 1st Appearance Ra's al Ghul."
  },
  {
    id: "mcs-7819204",
    source: "mycomicshop",
    title: "Swamp Thng #37 CGC 9.8 Typo Sleeper Listing Alan Moore",
    currentBid: 610.00,
    shippingCost: 14.00,
    bidCount: 5,
    secondsRemaining: 660, // < 15m On Deck!
    url: "https://www.mycomicshop.com/auctions/item?id=7819204",
    imageUrl: `${GCS_BASE}/D/DC/S/Swamp Thing (2nd Series)/37.jpg`,
    certNumber: "4019283088",
    fairMarketValue: 2400.00,
    anchorFmv: 2400.00,
    pricingSourceProvenance: "GPA Realized Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 1820,
    censusCount98: 245,
    censusHigher: 0,
    censusScarcityTier: "Typo Listing 'Swamp Thng'",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "MyComicShop Consignment Lot: Title cataloged as 'Swamp Thng #37' with missing 'i'."
  },

  // ==========================================
  // 4. COMICLINK (Auction Exchange & Focus)
  // ==========================================
  {
    id: "cl-5920101",
    source: "comiclink",
    title: "Batman #404 CGC 9.8 Year One Part 1 Frank Miller David Mazzucchelli",
    currentBid: 145.00,
    shippingCost: 18.00,
    bidCount: 6,
    secondsRemaining: 35, // < 1m Instant Snipe!
    url: "https://www.comiclink.com/auctions/item.asp?id=5920101",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/404.jpg`,
    certNumber: "3891024005",
    fairMarketValue: 340.00,
    anchorFmv: 340.00,
    pricingSourceProvenance: "ComicLink Exchange Realized Prices",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 1850,
    censusCount98: 340,
    censusHigher: 0,
    censusScarcityTier: "Copper Age Blueprint Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "ComicLink Focused Auction: CGC 9.8 White Pages. Frank Miller Batman Year One landmark."
  },
  {
    id: "cl-5920102",
    source: "comiclink",
    title: "Crisis on Infinite Earths #7 CGC 9.8 Death of Supergirl George Pérez",
    currentBid: 110.00,
    shippingCost: 18.00,
    bidCount: 5,
    secondsRemaining: 75, // < 2m Red Hot!
    url: "https://www.comiclink.com/auctions/item.asp?id=5920102",
    imageUrl: `${GCS_BASE}/D/DC/C/Crisis on Infinite Earths/7.jpg`,
    certNumber: "3748291002",
    fairMarketValue: 260.00,
    anchorFmv: 260.00,
    pricingSourceProvenance: "ComicLink Realized Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 2100,
    censusCount98: 420,
    censusHigher: 0,
    censusScarcityTier: "Iconic Pieta Cover Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "ComicLink Auction: CGC 9.8 White Pages. Iconic George Pérez cover art."
  },
  {
    id: "cl-5920103",
    source: "comiclink",
    title: "Batman #386 CGC 9.8 1st Black Mask Cracked Corner Slab Reholder Play",
    currentBid: 165.00,
    shippingCost: 18.00,
    bidCount: 7,
    secondsRemaining: 210, // < 5m Closing!
    url: "https://www.comiclink.com/auctions/item.asp?id=5920103",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/386.jpg`,
    certNumber: "3892014008",
    fairMarketValue: 420.00,
    anchorFmv: 420.00,
    pricingSourceProvenance: "ComicLink Auction Sales Archive",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 880,
    censusCount98: 120,
    censusHigher: 0,
    censusScarcityTier: "Copper Key 1st Black Mask",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "ComicLink Exchange: CGC 9.8 cracked corner slab shell. High-spread reholder arbitrage target."
  },

  // ==========================================
  // 5. SHORTBOXED (Verified Slab Desk)
  // ==========================================
  {
    id: "sb-391024",
    source: "shortboxed",
    title: "Batman Damned #1 CGC 9.8 Banned Bat-Nudity 1st Print Uncensored",
    currentBid: 85.00,
    shippingCost: 10.00,
    bidCount: 4,
    secondsRemaining: 50, // < 1m Instant Snipe!
    url: "https://shortboxed.com/book/391024",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman - Damned/1.jpg`,
    certNumber: "3920194881",
    fairMarketValue: 195.00,
    anchorFmv: 195.00,
    pricingSourceProvenance: "Shortboxed Verified Realized Transactions",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 2800,
    censusCount98: 910,
    censusHigher: 0,
    censusScarcityTier: "Modern Controversy Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Shortboxed Verified Desk: CGC 9.8 White Pages. Uncensored 1st printing."
  },
  {
    id: "sb-391025",
    source: "shortboxed",
    title: "Detective Comics #880 CGC 9.8 Jock Joker Cover Modern Grail",
    currentBid: 320.00,
    shippingCost: 12.00,
    bidCount: 9,
    secondsRemaining: 95, // < 2m Red Hot!
    url: "https://shortboxed.com/book/391025",
    imageUrl: `${GCS_BASE}/D/DC/D/Detective Comics/880.jpg`,
    certNumber: "3748291001",
    fairMarketValue: 650.00,
    anchorFmv: 650.00,
    pricingSourceProvenance: "Shortboxed & GPA Realized Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 1240,
    censusCount98: 260,
    censusHigher: 0,
    censusScarcityTier: "Modern Classic Cover Grail",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Shortboxed Direct: CGC 9.8 White Pages. Iconic Jock Joker bat-swarm face cover."
  },
  {
    id: "sb-391026",
    source: "shortboxed",
    title: "Batman #635 CGC 9.8 1st Red Hood Cracked Case Scuffed Holder",
    currentBid: 160.00,
    shippingCost: 12.00,
    bidCount: 6,
    secondsRemaining: 360, // < 10m Microwave!
    url: "https://shortboxed.com/book/391026",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/635.jpg`,
    certNumber: "3892019011",
    fairMarketValue: 380.00,
    anchorFmv: 380.00,
    pricingSourceProvenance: "Shortboxed Market Value Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 1680,
    censusCount98: 320,
    censusHigher: 0,
    censusScarcityTier: "Modern Red Hood Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Shortboxed Verified Desk: CGC 9.8 scuffed case and cracked top tab. Flawless reholder play."
  },

  // ==========================================
  // 6. WHATNOT (Sudden Death Auction Drops)
  // ==========================================
  {
    id: "wn-1092841",
    source: "whatnot",
    title: "Batman #497 CGC 9.8 Bane Breaks Batman's Back Sudden Drop",
    currentBid: 65.00,
    shippingCost: 8.50,
    bidCount: 8,
    secondsRemaining: 45, // < 1m Instant Snipe!
    url: "https://whatnot.com/live/comic-drop/1092841",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/497.jpg`,
    certNumber: "3819204002",
    fairMarketValue: 165.00,
    anchorFmv: 165.00,
    pricingSourceProvenance: "Whatnot Realized Comic Drop Stream",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 3100,
    censusCount98: 620,
    censusHigher: 0,
    censusScarcityTier: "Knightfall Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Whatnot Live Stream Sudden-Death Auction: CGC 9.8 White Pages. Instant snipe window closing."
  },
  {
    id: "wn-1092842",
    source: "whatnot",
    title: "Detective Comics #1000 CGC 9.8 Artgerm Variant Floor Loss Sale",
    currentBid: 42.00,
    shippingCost: 8.50,
    bidCount: 3,
    secondsRemaining: 115, // < 2m Red Hot!
    url: "https://whatnot.com/live/comic-drop/1092842",
    imageUrl: `${GCS_BASE}/D/DC/D/Detective Comics/1000-A.jpg`,
    certNumber: "3920194099",
    fairMarketValue: 120.00,
    anchorFmv: 120.00,
    pricingSourceProvenance: "Whatnot Realized Stream Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 1540,
    censusCount98: 510,
    censusHigher: 0,
    censusScarcityTier: "Sunk Cost (<$45 Slab)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Whatnot Flash Drop: CGC 9.8 Artgerm Catwoman foil variant. Total price below cost of grading."
  },

  // ==========================================
  // 7. PRISTINE AUCTION (10-Minute Countdown Clock)
  // ==========================================
  {
    id: "pa-682019",
    source: "pristine",
    title: "Batman #423 CBCS 9.8 Signed Todd McFarlane Witnessed Gold Label",
    currentBid: 680.00,
    shippingCost: 20.00,
    bidCount: 14,
    secondsRemaining: 58, // < 1m Instant Snipe!
    url: "https://www.pristineauction.com/auction/index/item/682019",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/423.jpg`,
    certNumber: "21-394810-001",
    fairMarketValue: 1650.00,
    anchorFmv: 1650.00,
    pricingSourceProvenance: "Pristine Auction Verified Signatures Archive",
    gradingCompany: "CBCS",
    resolvedGrade: 9.8,
    censusTotal: 420,
    censusCount98: 62,
    censusHigher: 0,
    censusScarcityTier: "Witnessed Gold Label Signature Series",
    isYellowLabel: true,
    signerName: "Todd McFarlane",
    signaturePremiumMultiplier: 1.5,
    itemDescription: "Pristine Daily Auction: CBCS 9.8 Witnessed Todd McFarlane signature in bold silver ink."
  },
  {
    id: "pa-682020",
    source: "pristine",
    title: "Batman #291 CGC 9.6 Broken Corner Shell Reholder Play 1st Where Were You",
    currentBid: 140.00,
    shippingCost: 18.00,
    bidCount: 5,
    secondsRemaining: 145, // < 5m Closing!
    url: "https://www.pristineauction.com/auction/index/item/682020",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/291.jpg`,
    certNumber: "3849201991",
    fairMarketValue: 340.00,
    anchorFmv: 340.00,
    pricingSourceProvenance: "Pristine Realized Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.6,
    censusTotal: 620,
    censusCount98: 48,
    censusHigher: 0,
    censusScarcityTier: "Bronze Age Classic Joker Trial",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Pristine Auction: CGC 9.6 broken shell corner. Internal well intact. Prime $25 reholder target."
  },

  // ==========================================
  // 8. FANATICS / GOLDIN / PWCC
  // ==========================================
  {
    id: "goldin-91024",
    source: "goldin",
    title: "Brave and the Bold #28 CBCS 9.4 1st Justice League of America Silver Age Grail",
    currentBid: 12500.00,
    shippingCost: 75.00,
    bidCount: 38,
    secondsRemaining: 70, // < 2m Red Hot!
    url: "https://goldin.co/item/brave-and-the-bold-28-cbcs-94-91024",
    imageUrl: `${GCS_BASE}/D/DC/B/Brave and the Bold, The/28.jpg`,
    certNumber: "19-482019-001",
    fairMarketValue: 28000.00,
    anchorFmv: 28000.00,
    pricingSourceProvenance: "Goldin Elite Comic Auctions & GPA Realized Sales",
    gradingCompany: "CBCS",
    resolvedGrade: 9.4,
    censusTotal: 840,
    censusCount98: 2,
    censusHigher: 0,
    censusScarcityTier: "Museum Grade Blue Chip Mega-Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Goldin Elite Session: CBCS 9.4 White Pages. 1st Appearance Justice League of America."
  },

  // ==========================================
  // 9. METROPOLIS COLLECTIBLES
  // ==========================================
  {
    id: "metro-104928",
    source: "metropolis",
    title: "Action Comics #242 CGC 9.4 1st Brainiac & Kandor Silver Age Landmark",
    currentBid: 3400.00,
    shippingCost: 35.00,
    bidCount: 18,
    secondsRemaining: 160, // < 5m Closing!
    url: "https://www.metropoliscomics.com/inventory/item/104928",
    imageUrl: `${GCS_BASE}/D/DC/A/Action Comics/242.jpg`,
    certNumber: "3649201044",
    fairMarketValue: 6800.00,
    anchorFmv: 6800.00,
    pricingSourceProvenance: "Metropolis Collectibles Realized Valuation Archive",
    gradingCompany: "CGC",
    resolvedGrade: 9.4,
    censusTotal: 580,
    censusCount98: 4,
    censusHigher: 0,
    censusScarcityTier: "Silver Age Historic Grail",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Metropolis Direct Auction: CGC 9.4 Off-White to White Pages. 1st Appearance Brainiac."
  },

  // ==========================================
  // 10. HIPCOMIC MARKETPLACE
  // ==========================================
  {
    id: "hip-581920",
    source: "hipcomic",
    title: "Batman Adventures #12 CBCS 9.4 1st Harley Quinn Copper Key",
    currentBid: 850.00,
    shippingCost: 16.00,
    bidCount: 11,
    secondsRemaining: 49, // < 1m Instant Snipe!
    url: "https://www.hipcomic.com/listing/batman-adventures-12-cbcs-94/581920",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman Adventures, The/12.jpg`,
    certNumber: "20-384910-002",
    fairMarketValue: 1850.00,
    anchorFmv: 1850.00,
    pricingSourceProvenance: "HipComic Verified Market Comps",
    gradingCompany: "CBCS",
    resolvedGrade: 9.4,
    censusTotal: 3400,
    censusCount98: 410,
    censusHigher: 0,
    censusScarcityTier: "Modern Age Grails (1st Harley Quinn)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "HipComic Live Auction: CBCS 9.4 White Pages. 1st Harley Quinn in continuity."
  },
  {
    id: "hip-581921",
    source: "hipcomic",
    title: "Batamn #357 CGC 9.6 1st Jason Todd Typo Sleeper Listing",
    currentBid: 145.00,
    shippingCost: 15.00,
    bidCount: 4,
    secondsRemaining: 480, // < 10m Microwave!
    url: "https://www.hipcomic.com/listing/batamn-357-cgc-96/581921",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/357.jpg`,
    certNumber: "3892019441",
    fairMarketValue: 320.00,
    anchorFmv: 320.00,
    pricingSourceProvenance: "HipComic Realized Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.6,
    censusTotal: 1100,
    censusCount98: 142,
    censusHigher: 0,
    censusScarcityTier: "Fat Finger Typo 'Batamn'",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "HipComic Store Listing: Misspelled title 'Batamn #357'. Zero competing search traffic."
  },

  // ==========================================
  // 11. MERCARI (Sleeper Relics)
  // ==========================================
  {
    id: "mer-829104",
    source: "mercari",
    title: "Batman: Shadow of the Bat #1 CGC 9.8 Sunk Cost Slabs 1st Victor Zsasz",
    currentBid: 34.00,
    shippingCost: 8.00,
    bidCount: 2,
    secondsRemaining: 52, // < 1m Instant Snipe!
    url: "https://www.mercari.com/us/item/m829104/",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman - Shadow of the Bat/1.jpg`,
    certNumber: "4019284001",
    fairMarketValue: 80.00,
    anchorFmv: 80.00,
    pricingSourceProvenance: "Mercari Realized Transactions",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 920,
    censusCount98: 280,
    censusHigher: 0,
    censusScarcityTier: "Sunk Cost (<$45 Slab)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "Mercari Seller Liquidation: CGC 9.8 White Pages with collector hologram. Seller taking loss below grading fee."
  },

  // ==========================================
  // 12. EBAY (Verified Authentic Seller Photos & Scraped Live Lots)
  // ==========================================
  {
    id: "ebay-4050632030",
    source: "ebay",
    title: "Batman/Deadpool #1 1of5 Blue Sketch Edition Signed Clay Mann CGC 9.8 SS",
    currentBid: 165.00,
    shippingCost: 15.00,
    bidCount: 12,
    secondsRemaining: 40, // < 1m Instant Snipe!
    url: "https://www.ebay.com/itm/4050632030",
    imageUrl: "https://i.ebayimg.com/images/g/e7UAAOSwD5pnPZvZ/s-l1600.jpg",
    certNumber: "4050632030",
    fairMarketValue: 1241.99,
    anchorFmv: 1241.99,
    pricingSourceProvenance: "GPA Realized Signature Index & Heritage Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 84,
    censusCount98: 28,
    censusHigher: 0,
    censusScarcityTier: "Top of Population (Witnessed Yellow Label)",
    isYellowLabel: true,
    signerName: "Clay Mann",
    signaturePremiumMultiplier: 1.65,
    itemDescription: "eBay Live Ending Auction: CGC Signature Series 9.8 Blue Sketch Edition signed by Clay Mann with custom sketch."
  },
  {
    id: "ebay-4050629701",
    source: "ebay",
    title: "Bloodshot #2 CGC 9.8 Mint 1993 Valiant Classic Key",
    currentBid: 4.99,
    shippingCost: 7.50,
    bidCount: 1,
    secondsRemaining: 65, // < 2m Red Hot!
    url: "https://www.ebay.com/itm/4050629701",
    imageUrl: "https://i.ebayimg.com/images/g/W4sAAeSwmR5p4jv2/s-l1600.jpg",
    certNumber: "4050629701",
    fairMarketValue: 95.00,
    anchorFmv: 95.00,
    pricingSourceProvenance: "GPA Analysis 90-Day Comp Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 142,
    censusCount98: 38,
    censusHigher: 0,
    censusScarcityTier: "Top of Population (9.8 Universal)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay Auction: CGC 9.8 White Pages. Ending immediately with only 1 bid."
  },
  {
    id: "ebay-4050629702",
    source: "ebay",
    title: "Batman #423 CGC 9.8 Cracked Case at Bottom Corner Reholder Play",
    currentBid: 440.00,
    shippingCost: 15.00,
    bidCount: 9,
    secondsRemaining: 85, // < 2m Red Hot!
    url: "https://www.ebay.com/itm/4050629702",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/423.jpg`,
    certNumber: "3892019401",
    fairMarketValue: 1250.00,
    anchorFmv: 1250.00,
    pricingSourceProvenance: "GPA Realized Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 3450,
    censusCount98: 412,
    censusHigher: 0,
    censusScarcityTier: "Cracked Case ($25 Reholder Arbitrage)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay Auction: CGC 9.8 with crack on bottom right bumper. Book untouched in sealed inner well. Huge $25 reholder spread."
  },
  {
    id: "ebay-4050629703",
    source: "ebay",
    title: "Avangers #1 CGC 9.4 Jack Kirby Typo Sleeper Listing",
    currentBid: 920.00,
    shippingCost: 20.00,
    bidCount: 6,
    secondsRemaining: 210, // < 5m Closing!
    url: "https://www.ebay.com/itm/4050629703",
    imageUrl: `${GCS_BASE}/D/DC/A/All-Star Comics/58.jpg`,
    certNumber: "3748291040",
    fairMarketValue: 3200.00,
    anchorFmv: 3200.00,
    pricingSourceProvenance: "Heritage Realized Archive",
    gradingCompany: "CGC",
    resolvedGrade: 9.4,
    censusTotal: 480,
    censusCount98: 8,
    censusHigher: 0,
    censusScarcityTier: "Fat Finger Typo 'Avangers'",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay Sleeper: Seller misspelled title as 'Avangers'. Zero automated saved search alerts firing."
  },
  {
    id: "ebay-4050629704",
    source: "ebay",
    title: "Silk #1 CGC 9.8 Peach Momoko Variant Marvel Landmark",
    currentBid: 140.00,
    shippingCost: 14.00,
    bidCount: 8,
    secondsRemaining: 340, // < 10m Microwave!
    url: "https://www.ebay.com/itm/4050629704",
    imageUrl: "https://i.ebayimg.com/images/g/Bq8AAOSwr8hnPZwP/s-l1600.jpg",
    certNumber: "4050632044",
    fairMarketValue: 310.00,
    anchorFmv: 310.00,
    pricingSourceProvenance: "GPA Realized Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 680,
    censusCount98: 190,
    censusHigher: 0,
    censusScarcityTier: "Modern Peach Momoko Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay Auction: CGC 9.8 White Pages. Peach Momoko virgin cover."
  },
  {
    id: "ebay-4050629705",
    source: "ebay",
    title: "Hulk #3 CGC 9.8 Ryan Ottley Variant 1st Titan Marvel Key",
    currentBid: 95.00,
    shippingCost: 12.00,
    bidCount: 5,
    secondsRemaining: 490, // < 10m Microwave!
    url: "https://www.ebay.com/itm/4050629705",
    imageUrl: "https://i.ebayimg.com/images/g/s5MAAOSwYyFnPZw7/s-l1600.jpg",
    certNumber: "4050632050",
    fairMarketValue: 240.00,
    anchorFmv: 240.00,
    pricingSourceProvenance: "GPA Analysis 90-Day Comp Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 480,
    censusCount98: 140,
    censusHigher: 0,
    censusScarcityTier: "Ryan Ottley 1st Titan Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay Auction: CGC 9.8 White Pages. 1st Titan (Deadliest Hulk incarnation)."
  },

  // ==========================================
  // 13. EBAY CANADA (CAD C$ / CPVs & Canadian Heroes)
  // ==========================================
  {
    id: "ebay-ca-9102401",
    source: "ebay_ca",
    title: "Alpha Flight #1 CGC 9.8 1st Canadian Superheroes Team John Byrne",
    currentBid: 102.20, // Converted to USD
    originalBid: 140.00, // In CAD C$
    currency: "CAD",
    originalCurrencySymbol: "C$",
    exchangeRateToUsd: 0.73,
    internationalRegion: "CA",
    isCanadianSuperhero: true,
    shippingCost: 15.00,
    bidCount: 7,
    secondsRemaining: 44, // < 1m Instant Snipe!
    url: "https://www.ebay.ca/itm/9102401",
    imageUrl: `${GCS_BASE}/D/DC/A/All-Star Comics/58.jpg`,
    certNumber: "3849102011",
    fairMarketValue: 280.00,
    anchorFmv: 280.00,
    pricingSourceProvenance: "eBay Canada & GPA 90-Day Comp Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 1240,
    censusCount98: 240,
    censusHigher: 0,
    censusScarcityTier: "Canadian Superhero Landmark",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay Canada Live Ending: CGC 9.8 White Pages. 1st Solo Series Alpha Flight (Guardian, Sasquatch, Shaman, Snowbird, Puck, Northstar). Bid in C$140 CAD converted to $102.20 USD."
  },
  {
    id: "ebay-ca-9102402",
    source: "ebay_ca",
    title: "Captain Canuck #1 CGC 9.6 1st Canadian Sovereign Hero Richard Comely",
    currentBid: 135.05,
    originalBid: 185.00,
    currency: "CAD",
    originalCurrencySymbol: "C$",
    exchangeRateToUsd: 0.73,
    internationalRegion: "CA",
    isCanadianSuperhero: true,
    shippingCost: 18.00,
    bidCount: 5,
    secondsRemaining: 95, // < 2m Red Hot!
    url: "https://www.ebay.ca/itm/9102402",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/423.jpg`,
    certNumber: "3748291088",
    fairMarketValue: 420.00,
    anchorFmv: 420.00,
    pricingSourceProvenance: "Canadian Comic Comp Index & Heritage Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.6,
    censusTotal: 410,
    censusCount98: 22,
    censusHigher: 0,
    censusScarcityTier: "Sovereign Canadian Bronze Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay Canada Auction: CGC 9.6 White Pages. Historic 1st Appearance Captain Canuck (1975). Bid in C$185 CAD = $135.05 USD."
  },
  {
    id: "ebay-ca-9102403",
    source: "ebay_ca",
    title: "Batman #423 75¢ CPV Canadian Price Variant CGC 9.8 Damaged Holder",
    currentBid: 547.50,
    originalBid: 750.00,
    currency: "CAD",
    originalCurrencySymbol: "C$",
    exchangeRateToUsd: 0.73,
    internationalRegion: "CA",
    isCanadianPriceVariant: true,
    shippingCost: 20.00,
    bidCount: 11,
    secondsRemaining: 180, // < 5m Closing!
    url: "https://www.ebay.ca/itm/9102403",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/423.jpg`,
    certNumber: "3892019477",
    fairMarketValue: 1850.00,
    anchorFmv: 1850.00,
    pricingSourceProvenance: "GPA CPV Index & Heritage Signature Comps",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 180,
    censusCount98: 18,
    censusHigher: 0,
    censusScarcityTier: "Ultra-Rare Canadian Price Variant (CPV)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay Canada: Rare 75¢ Canadian Price Variant newsstand edition. CGC 9.8 with scuffed casing and damaged holder. Flawless comic inside. Incredible $25 reholder arbitrage against $1,850 CPV FMV!"
  },

  // ==========================================
  // 14. EBAY UK (GBP £ / Pence Copies & 2000 AD)
  // ==========================================
  {
    id: "ebay-uk-8291041",
    source: "ebay_uk",
    title: "2000 AD #2 Prog 2 CGC 9.4 1st Judge Dredd British Mega-Key",
    currentBid: 845.00,
    originalBid: 650.00,
    currency: "GBP",
    originalCurrencySymbol: "£",
    exchangeRateToUsd: 1.30,
    internationalRegion: "UK",
    isForeignLanguageEdition: false,
    shippingCost: 35.00,
    bidCount: 22,
    secondsRemaining: 56, // < 1m Instant Snipe!
    url: "https://www.ebay.co.uk/itm/8291041",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/181.jpg`,
    certNumber: "3649201088",
    fairMarketValue: 2400.00,
    anchorFmv: 2400.00,
    pricingSourceProvenance: "eBay UK Realized Comps & CompPal Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.4,
    censusTotal: 380,
    censusCount98: 4,
    censusHigher: 0,
    censusScarcityTier: "British Holy Grail Key (1st Judge Dredd)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay UK Live Auction: CGC 9.4 Off-White to White Pages. Complete Prog 2 with 1st Judge Dredd. Ending immediately in £650 GBP = $845.00 USD."
  },
  {
    id: "ebay-uk-8291042",
    source: "ebay_uk",
    title: "Captain Britain #1 CGC 9.6 1st Brian Braddock Chris Claremont Damaged Case",
    currentBid: 494.00,
    originalBid: 380.00,
    currency: "GBP",
    originalCurrencySymbol: "£",
    exchangeRateToUsd: 1.30,
    internationalRegion: "UK",
    isForeignLanguageEdition: false,
    shippingCost: 28.00,
    bidCount: 12,
    secondsRemaining: 150, // < 5m Closing!
    url: "https://www.ebay.co.uk/itm/8291042",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/232.jpg`,
    certNumber: "3748291099",
    fairMarketValue: 1200.00,
    anchorFmv: 1200.00,
    pricingSourceProvenance: "eBay UK & Heritage International Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.6,
    censusTotal: 520,
    censusCount98: 34,
    censusHigher: 0,
    censusScarcityTier: "1st Captain Britain (Damaged Case Reholder)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay UK Auction: CGC 9.6 with cracked plastic edge on casing / damaged case. Complete with free boomerang mask. £380 GBP converted to $494.00 USD."
  },

  // ==========================================
  // 15. EBAY FRANCE (EUR € / Lug Editions & French Translations)
  // ==========================================
  {
    id: "ebay-fr-7102941",
    source: "ebay_fr",
    title: "Strange #1 CGC 9.2 Editions Lug 1970 L'Araignee Les Vengeurs French Key",
    translatedTitle: "The Amazing Spider-Man & The Avengers (French Lug Premiere #1)",
    currentBid: 926.50,
    originalBid: 850.00,
    currency: "EUR",
    originalCurrencySymbol: "€",
    exchangeRateToUsd: 1.09,
    internationalRegion: "FR",
    isForeignLanguageEdition: true,
    shippingCost: 32.00,
    bidCount: 16,
    secondsRemaining: 48, // < 1m Instant Snipe!
    url: "https://www.ebay.fr/itm/7102941",
    imageUrl: `${GCS_BASE}/D/DC/S/Swamp Thing (2nd Series)/37.jpg`,
    certNumber: "3649201999",
    fairMarketValue: 2800.00,
    anchorFmv: 2800.00,
    pricingSourceProvenance: "eBay France Certified Lug Comp Index",
    gradingCompany: "CGC",
    resolvedGrade: 9.2,
    censusTotal: 140,
    censusCount98: 0,
    censusHigher: 0,
    censusScarcityTier: "French Silver Age Holy Grail (Editions Lug)",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay France Vente aux enchères: CGC 9.2. Éditions Lug 1970 N°1 avec L'Araignée (Spider-Man), Les Vengeurs (Avengers), et Le Surfer d'Argent. Enchère en cours €850 EUR = $926.50 USD."
  },
  {
    id: "ebay-fr-7102942",
    source: "ebay_fr",
    title: "Serval #1 CGC 9.8 Semic France Damaged Holder Case Crack Reholder Play",
    translatedTitle: "Wolverine #1 (French Semic Sovereign Edition)",
    currentBid: 119.90,
    originalBid: 110.00,
    currency: "EUR",
    originalCurrencySymbol: "€",
    exchangeRateToUsd: 1.09,
    internationalRegion: "FR",
    isForeignLanguageEdition: true,
    shippingCost: 20.00,
    bidCount: 6,
    secondsRemaining: 230, // < 5m Closing!
    url: "https://www.ebay.fr/itm/7102942",
    imageUrl: `${GCS_BASE}/D/DC/B/Batman/386.jpg`,
    certNumber: "3892019888",
    fairMarketValue: 350.00,
    anchorFmv: 350.00,
    pricingSourceProvenance: "eBay France Realized Sales",
    gradingCompany: "CGC",
    resolvedGrade: 9.8,
    censusTotal: 280,
    censusCount98: 44,
    censusHigher: 0,
    censusScarcityTier: "Damaged Holder French Semic Key",
    isYellowLabel: false,
    signerName: "",
    signaturePremiumMultiplier: null,
    itemDescription: "eBay France: CGC 9.8 Serval (Wolverine) N°1 avec boîtier fissuré / damaged holder. Superbe opportunité de reholder à $25 pour dégager 100%+ de profit net. €110 EUR = $119.90 USD."
  }
];

function buildAndSyncAuctions() {
  const targetPath = path.resolve(process.cwd(), "data/live_auctions.json");
  fs.writeFileSync(targetPath, JSON.stringify(MULTI_SOURCE_AUCTIONS, null, 2), "utf-8");
  console.log(`Successfully generated and synced ${MULTI_SOURCE_AUCTIONS.length} multi-source live auctions to ${targetPath}`);
}

buildAndSyncAuctions();
