import Link from "next/link";
import { ArrowUpRight, Database, Search } from "lucide-react";
import { getMarketIntelligence } from "@/lib/dashboard/queries";
import { getFirms } from "@/lib/panel-profits/queries";

export const dynamic = "force-dynamic";

export default async function ResearchPage() {
  const [assets, rawFirms] = await Promise.all([getMarketIntelligence(30), getFirms()]);
  const firms = rawFirms.filter(Boolean);
  return <main className="mx-auto w-full max-w-7xl px-4 py-10 sm:px-6 lg:px-8"><header className="border-b border-slate-800 pb-7"><p className="text-[10px] uppercase tracking-[0.28em] text-sky-300">Research terminal / Clean universe</p><h1 className="mt-3 text-4xl text-slate-100">Investigate the operating world</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-400">Catalog records and firm-prefixed identity systems are shown from the current Clean contracts. Unavailable market layers are not inferred.</p></header><div className="mt-8 grid gap-8 lg:grid-cols-2"><section><div className="mb-3 flex items-center gap-2"><Database className="h-4 w-4 text-sky-300" /><h2 className="text-sm uppercase tracking-[0.16em] text-slate-200">Catalog assets</h2></div><div className="divide-y divide-slate-800 border-y border-slate-800">{assets.map((asset) => <Link key={asset.id} href={`/comics/${asset.id}`} className="flex items-center justify-between gap-3 p-4 hover:bg-[#0b0f15]"><div><p className="text-sm text-slate-100">{asset.series} <span className="text-slate-500">#{asset.issueNumber}</span></p><p className="mt-1 text-xs text-slate-500">{asset.publisher || "Publisher unlisted"} · {asset.source || "Clean catalog"}</p></div><span className="flex items-center gap-2 text-xs text-emerald-300">{asset.indexValue === null ? "Unpriced" : `$${asset.indexValue.toFixed(2)}`}<ArrowUpRight className="h-3.5 w-3.5" /></span></Link>)}{!assets.length && <p className="p-5 text-sm text-slate-500">No Clean catalog records are available.</p>}</div></section><section><div className="mb-3 flex items-center gap-2"><Search className="h-4 w-4 text-amber-300" /><h2 className="text-sm uppercase tracking-[0.16em] text-slate-200">Firm identities</h2></div><div className="divide-y divide-slate-800 border-y border-slate-800">{firms.map((firm) => <Link key={firm!.firm_id} href={`/firms/${firm!.firm_id}`} className="flex items-center justify-between gap-3 p-4 hover:bg-[#0b0f15]"><div><p className="text-sm text-slate-100">{firm!.firm_name}</p><p className="mt-1 text-xs text-slate-500">{firm!.mythology || "Clean firm identity"} · {firm!.total_brokers} brokers</p></div><ArrowUpRight className="h-3.5 w-3.5 text-slate-600" /></Link>)}{!firms.length && <p className="p-5 text-sm text-slate-500">No Clean firm identity records are available.</p>}</div></section></div></main>;
}
